server:
  port: 80

eureka:
  client:
    #表示是否将自己注册在服务EurekaServer 默认为true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

#设置fegin客户端超时时间
ribbon:
#指的是建立连接的时间，适用于网络状况正常的情况下，两端连接所使用的时间。
  ReadTimeout: 5000
#指的是建立连接后从服务器，读取到可用资源的时间
  ConnectTimeout: 5000
logging:
  level:
    com.example.springcloud.service.PaymentFeginService: debug  #fegin日志以什么级别监控那个接口








